addpath(genpath('./bench/'));
addpath(genpath('./piotr_toolbox/'));
addpath('daisy');
run('vlfeat/toolbox/vl_setup'); 
train_img_dir = '../data/BSDS500/images/train/';
test_img_dir  = '../data/BSDS500/images/small_test/';
train_gt_dir = '../data/BSDS500/groundTruth/train/';
test_gt_dir  = '../data/BSDS500/groundTruth/test/';
feature_params = struct('R', 15, 'RQ', 3, 'TQ', 8, 'HQ', 8, 'SI', 1, 'LI', 1, 'NT', 0, 'CR', 7);
num_sketch_tokens = 1;
disp('parameters are assigned');